all: 
	javac -source 1.4 -classpath ../lib -g:none *.java

accum:
	javac -classpath ../lib -d ../lib -g AccumulateRTree.java

trans:
	javac -classpath ../lib -d ../lib -g TransitionMatrix.java

debug:
	javac -source 1.4 -classpath ../lib -g *.java

clean:
	rm -rf *.class

